// src/components/reports/AuditReportPdf.tsx

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font
} from '@react-pdf/renderer';

import { AuditLogEntry, AuditFilters, AuditPagination } from '@/types/audit';
import path from 'path';

Font.register({
  family: 'Roboto',
  fonts: [
    {
      src: path.join(process.cwd(), 'public/fonts/Roboto-Regular.ttf'),
    },
    {
      src: path.join(process.cwd(), 'public/fonts/Roboto-Bold.ttf'),
      fontWeight: 'bold',
    },
  ],
});

type Props = {
  logs: AuditLogEntry[];
  filters?: AuditFilters;
  pagination: AuditPagination;
  generatedAt: string;
  generatedBy?: string;
};

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 10,
    fontFamily: 'Roboto',
  },

  header: {
    marginBottom: 16,
  },

  title: {
    fontSize: 18,
    marginBottom: 8,
  },

  section: {
    marginBottom: 10,
  },

  label: {
    fontWeight: 'bold',
  },

  error: {
    color: 'red'
  },

  entry: {
    borderBottom: '1 solid #ccc',
    paddingBottom: 10,
    marginBottom: 10,
  },

  metadata: {
    fontSize: 9,
    color: 'gray',
    marginTop: 4,
  },

  mono: {
    fontFamily: 'Courier',
  },
});


/** 🔧 helpers */

function formatDate(date?: string) {
  if (!date) return '-';
  //return new Date(date).toISOString();
  return new Date(date).toLocaleString();
}

function formatAction(action: string) {
  return action.charAt(0) + action.slice(1).toLowerCase() + 'd';
}

function buildChanges(entry: AuditLogEntry) {
  const { old_value, new_value } = entry;

  if (!old_value || !new_value) return [];

  const changes: { field: string; old: unknown; new: unknown }[] = [];

  const keys = new Set([
    ...Object.keys(old_value),
    ...Object.keys(new_value),
  ]);

  keys.forEach((key) => {
    const oldVal = old_value[key];
    const newVal = new_value[key];

    if (JSON.stringify(oldVal) !== JSON.stringify(newVal)) {
      changes.push({
        field: key,
        old: oldVal,
        new: newVal,
      });
    }
  });

  return changes;
}

/** 📄 Header */

function Header({
  filters,
  pagination,
  generatedAt,
  generatedBy,
}: {
  filters?: AuditFilters;
  pagination: AuditPagination;
  generatedAt: string;
  generatedBy?: string;
}) {
  return (
    <View style={styles.header}>
      <Text style={styles.title}>Audit Report</Text>

      <View style={styles.section}>
        <Text>
          <Text style={styles.label}>Generated at: </Text>
          {formatDate(generatedAt)}
        </Text>

        {generatedBy && (
          <Text>
            <Text style={styles.label}>Generated by: </Text>
            {generatedBy}
          </Text>
        )}

        <Text>
          <Text style={styles.label}>Total records: </Text>
          {pagination.total}
        </Text>
      </View>

      {filters && (
        <View style={styles.section}>
          <Text style={styles.label}>Filters:</Text>

          <Text>
            Date: {filters.startDate || 'ALL'} →{' '}
            {filters.endDate || 'ALL'}
          </Text>

          <Text>
            Study: {filters.studyId || 'ALL'} | Site:{' '}
            {filters.siteId || 'ALL'}
          </Text>

          <Text>
            Action: {filters.action || 'ALL'} | Status:{' '}
            {filters.status || 'ALL'}
          </Text>

          {filters.userEmail && (
            <Text>User: {filters.userEmail}</Text>
          )}
        </View>
      )}
    </View>
  );
}


/** 📌 Entry */

function Entry({ entry }: { entry: AuditLogEntry }) {
  const changes = buildChanges(entry);

  return (
    <View style={styles.entry}>
      <Text>
        <Text style={styles.label}>Date: </Text>
        {formatDate(entry.created_at)}
      </Text>

      <Text>
        <Text style={styles.label}>User: </Text>
        {entry.user_email}
      </Text>

      <Text>
        <Text style={styles.label}>Action: </Text>
        {formatAction(entry.action)}
      </Text>

      <Text>
        <Text style={styles.label}>Entity: </Text>
          {entry.entity_type === 'document'
            ? entry.document_name || entry.entity_id
            : entry.entity_id}
        </Text>

      <Text>
        <Text style={styles.label}>Study: </Text>
        {entry.study_protocol || entry.study_id} / Site {entry.site_name || entry.site_id}
      </Text>

      <Text>
        <Text style={styles.label}>Site: </Text>
        {entry.site_name || entry.site_id}
      </Text>


      <Text>
        <Text style={styles.label}>Status: </Text>
        {entry.status}
      </Text>

      {/* ❗ error */}
      {entry.status === 'FAILURE' && entry.error_message && (
        <Text>
          <Text style={[styles.label, styles.error]}>Error: </Text>
          {entry.error_message}
        </Text>
      )}

      {/* ❗ reason */}
      {entry.reason && (
        <Text>
          <Text style={styles.label}>Reason: </Text>
          {entry.reason}
        </Text>
      )}

      {/* ✅ changes */}
      {changes.length > 0 && (
        <View>
          <Text style={styles.label}>Changes:</Text>

          {changes.map((c, i) => (
            <Text key={i}>
              - {c.field}: {String(c.old)} → {String(c.new)}
            </Text>
          ))}
        </View>
      )}

      {/* metadata */}
      <View style={styles.metadata}>
        <Text>IP: {entry.ip_address}</Text>

        {/* <Text>Session: {entry.session_id}</Text> */}

        <Text style={styles.mono}>
          Audit ID: {entry.audit_id}
        </Text>
      </View>
    </View>
  );
}


/** 📄 MAIN */

export function AuditReportPdf({
  logs,
  filters,
  pagination,
  generatedAt,
  generatedBy,
}: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Header
          filters={filters}
          pagination={pagination}
          generatedAt={generatedAt}
          generatedBy={generatedBy}
        />

        {logs.map((entry, i) => (
          <Entry key={entry.audit_id ?? i} entry={entry} />
        ))}
      </Page>
    </Document>
  );
}