// lib/email/templates/digest-email.tsx

import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Img,
} from '@react-email/components';
import { EMAIL_LOGO_URL } from '@/lib/email/constants';

type DigestEmailProps = {
  userName: string;
  appUrl: string;
  newDocuments: any[];
  updatedDocuments: any[];
  archivedDocuments: any[];
};

export const DigestEmail = ({
  userName,
  appUrl,
  newDocuments,
  updatedDocuments,
  archivedDocuments,
}: DigestEmailProps) => {
  const total =
    newDocuments.length +
    updatedDocuments.length +
    archivedDocuments.length;

  const previewText = `You have ${total} update${
    total !== 1 ? 's' : ''
  } in ExploreTMF`;

  return (
    <Html>
      <Head />
      <Preview>{previewText}</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={header}>
            <Img
              src={EMAIL_LOGO_URL}
              alt="ExploreTMF Logo"
              width="64"
              height="64"
              style={{ marginBottom: '12px' }}
            />
            <Text style={logo}>ExploreTMF</Text>
          </Section>

          {/* Content */}
          <Section style={content}>
            <Text style={heading}>Daily Activity Summary</Text>

            <Text style={paragraph}>
              Hello {userName},
            </Text>

            <Text style={paragraph}>
              Here is a summary of document activity in your studies over the last 24 hours:
            </Text>

            {/* Summary Box */}
            <Section style={summaryBox}>
              <Text style={summaryItem}>
                📄 New documents: <strong>{newDocuments.length}</strong>
              </Text>
              <Text style={summaryItem}>
                📦 Updated versions: <strong>{updatedDocuments.length}</strong>
              </Text>
              <Text style={summaryItem}>
                🗂 Archived: <strong>{archivedDocuments.length}</strong>
              </Text>
            </Section>

            {/* New Documents */}
            {newDocuments.length > 0 && (
              <>
                <Text style={sectionHeading}>📄 New Documents</Text>
                {newDocuments.slice(0, 10).map((doc: any) => (
                  <Text key={doc.id} style={listItem}>
                    • {doc.document_name} (Study {doc.study_id})
                  </Text>
                ))}
              </>
            )}

            {/* Updated Documents */}
            {updatedDocuments.length > 0 && (
              <>
                <Text style={sectionHeading}>📦 Updated Documents</Text>
                {updatedDocuments.slice(0, 10).map((doc: any) => (
                  <Text key={doc.id} style={listItem}>
                    • {doc.document_name} (v{doc.document_number})
                  </Text>
                ))}
              </>
            )}

            {/* Archived */}
            {archivedDocuments.length > 0 && (
              <>
                <Text style={sectionHeading}>🗂 Archived Documents</Text>
                {archivedDocuments.slice(0, 10).map((doc: any) => (
                  <Text key={doc.id} style={listItem}>
                    • {doc.folder_name}
                  </Text>
                ))}
              </>
            )}

            {/* Button */}
            <Section style={buttonContainer}>
              <Button style={button} href={appUrl}>
                Open ExploreTMF
              </Button>
            </Section>

            <Hr style={divider} />

            <Text style={paragraph}>
              You are receiving this email because you are subscribed to daily notifications.
            </Text>
          </Section>

          {/* Footer */}
          <Section style={footer}>
            <Hr style={footerDivider} />
            <Text style={footerText}>
              © {new Date().getFullYear()} ExploreTMF
            </Text>
            <Text style={footerDisclaimer}>
              This message is automatically generated by the ExploreTMF system.
              If you think it was sent incorrectly, please contact your ExploreTMF administrators.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

//
// Styles (почти те же, плюс новые блоки)
//

const main = {
  backgroundColor: '#f3f4f6',
  fontFamily:
    '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  marginTop: '40px',
  marginBottom: '40px',
  borderRadius: '8px',
  overflow: 'hidden',
  maxWidth: '600px',
  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
};

const header = {
  backgroundColor: '#667eea',
  padding: '32px 40px',
  textAlign: 'center' as const,
};

const logo = {
  color: '#ffffff',
  fontSize: '32px',
  fontWeight: '800',
  margin: '0',
  letterSpacing: '1px',
};

const content = {
  padding: '40px',
};

const heading = {
  color: '#2d3748',
  fontSize: '24px',
  fontWeight: '700',
  margin: '0 0 20px 0',
};

const paragraph = {
  color: '#4a5568',
  fontSize: '16px',
  lineHeight: '24px',
  margin: '0 0 16px 0',
};

const summaryBox = {
  backgroundColor: '#f7fafc',
  border: '1px solid #e2e8f0',
  borderRadius: '6px',
  padding: '16px',
  margin: '20px 0',
};

const summaryItem = {
  fontSize: '14px',
  margin: '6px 0',
  color: '#2d3748',
};

const sectionHeading = {
  fontSize: '16px',
  fontWeight: '600',
  margin: '20px 0 10px 0',
  color: '#2d3748',
};

const listItem = {
  fontSize: '14px',
  color: '#4a5568',
  margin: '4px 0',
};

const buttonContainer = {
  textAlign: 'center' as const,
  margin: '32px 0',
};

const button = {
  backgroundColor: '#667eea',
  borderRadius: '6px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '14px 32px',
};

const divider = {
  borderColor: '#e2e8f0',
  margin: '24px 0',
};

const footer = {
  backgroundColor: '#f7fafc',
  padding: '24px 40px',
  borderTop: '1px solid #e2e8f0',
};

const footerDivider = {
  borderColor: '#e2e8f0',
  margin: '0 0 12px 0',
};

const footerText = {
  color: '#a0aec0',
  fontSize: '12px',
  lineHeight: '20px',
  margin: '4px 0',
  textAlign: 'center' as const,
};

const footerDisclaimer = {
  color: '#a0aec0',
  fontSize: '11px',
  lineHeight: '18px',
  margin: '8px 0 0 0',
  textAlign: 'center' as const,
};