// lib/email/templates/document-review.tsx
import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Section,
  Text,
  Button,
  Hr,
  Img,
} from '@react-email/components';
import { DocumentReviewEmailData } from '../types';
import { EMAIL_LOGO_URL } from '@/lib/email/constants';

export const DocumentReviewEmail = ({
  recipientName,
  documents,
  reviewDeadline,
  comments,
}: DocumentReviewEmailData) => {
  const previewText = `Document${documents.length > 1 ? 's' : ''} pending your review`;
  const studyTitle = documents[0]?.studyTitle || 'Clinical Study';

  return (
    <Html>
      <Head />
      <Preview>{previewText}</Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={header}>
            <Img
              src={EMAIL_LOGO_URL}
              alt="ExploreTMF Logo"
              width="64"
              height="64"
              style={{ marginBottom: '12px' }}
            />
            <Text style={logo}>ExploreTMF</Text>
          </Section>

          {/* Content */}
          <Section style={content}>
            <Text style={heading}>Document{documents.length > 1 ? 's' : ''} Pending Your Review</Text>
            
            <Text style={paragraph}>
              Hello {recipientName},
            </Text>
            <Text style={paragraph}>
              {documents.length > 1 
                ? `${documents.length} documents have been` 
                : `A document has been`} submitted for your review in <strong>{studyTitle}</strong>.
            </Text>

            {reviewDeadline && (
              <Section style={deadlineBox}>
                <Text style={deadlineText}>
                  📅 <strong>Review Deadline:</strong> {reviewDeadline}
                </Text>
              </Section>
            )}

            {/* Document List */}
            <Section style={documentList}>
              {documents.map((doc, index) => (
                <Section key={index} style={documentItem}>
                  <Text style={documentName}>{doc.documentName}</Text>
                  {doc.documentType && (
                    <Text style={documentMeta}>Type: {doc.documentType}</Text>
                  )}
                  <Text style={documentMeta}>
                    Submitted by {doc.uploadedBy} • {doc.uploadedAt}
                  </Text>
                  {documents.length > 1 && index < documents.length - 1 && (
                    <Hr style={documentDivider} />
                  )}
                </Section>
              ))}
            </Section>

            {comments && (
              <Section style={commentsBox}>
                <Text style={commentsHeading}>Reviewer Comments:</Text>
                <Text style={commentsText}>{comments}</Text>
              </Section>
            )}

            <Section style={buttonContainer}>
              <Button style={button} href={documents[0]?.documentUrl || '#'}>
                Review Document{documents.length > 1 ? 's' : ''}
              </Button>
            </Section>

            <Hr style={divider} />

            <Text style={paragraph}>
              Please review the document{documents.length > 1 ? 's' : ''} and provide your feedback before the deadline.
            </Text>
          </Section>

          {/* Footer */}
          <Section style={footer}>
            <Hr style={footerDivider} />
            <Text style={footerText}>
              © {new Date().getFullYear()} ExploreTMF
            </Text>
            <Text style={footerDisclaimer}>
              This message is automatically generated by the ExploreTMF system.
              If you think it was sent incorrectly, please contact your ExploreTMF administrators.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default DocumentReviewEmail;

// Styles
const main = {
  backgroundColor: '#f3f4f6',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  marginTop: '40px',
  marginBottom: '40px',
  borderRadius: '8px',
  overflow: 'hidden',
  maxWidth: '600px',
  boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
};

const header = {
  backgroundColor: '#667eea',
  padding: '32px 40px',
  textAlign: 'center' as const,
};

const logo = {
  color: '#ffffff',
  fontSize: '32px',
  fontWeight: '800',
  margin: '0',
  letterSpacing: '1px',
};

const content = {
  padding: '40px',
};

const heading = {
  color: '#2d3748',
  fontSize: '24px',
  fontWeight: '700',
  margin: '0 0 20px 0',
};

const paragraph = {
  color: '#4a5568',
  fontSize: '16px',
  lineHeight: '24px',
  margin: '0 0 16px 0',
};

const deadlineBox = {
  backgroundColor: '#ebf8ff',
  border: '1px solid #90cdf4',
  borderRadius: '6px',
  padding: '16px',
  margin: '24px 0',
};

const deadlineText = {
  color: '#2c5282',
  fontSize: '14px',
  lineHeight: '20px',
  margin: '0',
};

const documentList = {
  backgroundColor: '#f7fafc',
  border: '1px solid #e2e8f0',
  borderRadius: '6px',
  padding: '20px',
  margin: '24px 0',
};

const documentItem = {
  padding: '12px 0',
};

const documentName = {
  color: '#2d3748',
  fontSize: '16px',
  fontWeight: '600',
  margin: '0 0 8px 0',
};

const documentMeta = {
  color: '#718096',
  fontSize: '14px',
  margin: '4px 0',
};

const documentDivider = {
  borderColor: '#e2e8f0',
  margin: '16px 0',
};

const commentsBox = {
  backgroundColor: '#f0fff4',
  border: '1px solid #9ae6b4',
  borderRadius: '6px',
  padding: '16px',
  margin: '24px 0',
};

const commentsHeading = {
  color: '#22543d',
  fontSize: '14px',
  fontWeight: '600',
  margin: '0 0 8px 0',
};

const commentsText = {
  color: '#276749',
  fontSize: '14px',
  lineHeight: '20px',
  margin: '0',
};

const buttonContainer = {
  textAlign: 'center' as const,
  margin: '32px 0',
};

const button = {
  backgroundColor: '#667eea',
  borderRadius: '6px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '14px 32px',
};

const divider = {
  borderColor: '#e2e8f0',
  margin: '24px 0',
};

const footer = {
  backgroundColor: '#f7fafc',
  padding: '24px 40px',
  borderTop: '1px solid #e2e8f0',
};

const footerDivider = {
  borderColor: '#e2e8f0',
  margin: '0 0 12px 0',
};

const footerText = {
  color: '#a0aec0',
  fontSize: '12px',
  lineHeight: '20px',
  margin: '4px 0',
  textAlign: 'center' as const,
};

const footerDisclaimer = {
  color: '#a0aec0',
  fontSize: '11px',
  lineHeight: '18px',
  margin: '8px 0 0 0',
  textAlign: 'center' as const,
};
