// lib/email/templates/EmailFooter.tsx
import { Section, Hr, Text } from '@react-email/components';
import { footer, footerDivider, footerText, footerDisclaimer } from './styles';

export const EmailFooter = () => (
  <Section style={footer}>
    <Hr style={footerDivider} />
    <Text style={footerText}>
      &copy; {new Date().getFullYear()} ExploreTMF
    </Text>
    <Text style={footerDisclaimer}>
      This message is automatically generated by the ExploreTMF system.
      If you think it was sent incorrectly, please contact your ExploreTMF administrators.
    </Text>
  </Section>
);

export default EmailFooter;
